const actionTypes = {
  GOT_CURRENT_LOCATION: 'GOT_CURRENT_LOCATION',
  TYPED_TO: 'TYPED_TO',
  TYPED_FROM: 'TYPED_TO',
  SET_VALUE_OF_TO: 'SET_VALUE_OF_TO',
  CHANGED_MARKER_LOCATION: 'CHANGED_MARKER_LOCATION',
  SAVED_ALARM_SETTING: 'SAVED_ALARM_SETTING',
  GOT_DIRECTIONS: 'GOT_DIRECTIONS'
};

export default actionTypes;
