const actionTypes = {
  LOGIN: 'LOGIN',
  LOADED_VIDEO_DATA: 'LOADED_VIDEO_DATA',
  LOADED_DICTIONARY_DATA: 'LOADED_DICTIONARY_DATA',
  TYPED_WORD: 'TYPED_WORD',
  CHECKED_LANGUAGE: 'CHECKED_LANGUAGE',
  CHECKED_CATEGORY: 'CHECKED_CATEGORY',
  REQUEST_VIDEOS: 'REQUEST_VIDEOS',
  REQUEST_POST_WORD: 'REQUEST_POST_WORD',
  REQUEST_DELETE_WORD: 'REQUEST_DELETE_WORD',
  MOVE_VIDEO_START_TIME: 'MOVE_VIDEO_START_TIME',
  UPDATE_CURRENT_VALUE: 'UPDATE_CURRENT_VALUE',
  UPDATE_VIDEO_ORDER: 'UPDATE_VIDEO_ORDER',
  REMOVE_WORD: 'REMOVE_WORD',
  ADD_WORD: 'ADD_WORD',
  READY_TO_SHOW_MODAL: 'READY_TO_SHOW_MODAL',
  NOT_READY_TO_SHOW_MODAL: 'NOT_READY_TO_SHOW_MODAL',
  UPDATE_MODAL_MESSAGE: 'UPDATE_MODAL_MESSAGE',
};

export default actionTypes;
